---
- name: Set facts according to CentOS variant
  set_fact:
    baseURI: >-
      {% if centos_variant == "stream" -%}
      https://cloud.centos.org/centos/{{ os_version }}-stream/x86_64/images/
      {% else -%}
      http://cloud.centos.org/centos/{{ os_version }}/x86_64/images/
      {% endif -%}
    destImg: >-
      {%- if centos_variant == "stream" -%}
      centos-{{ os_version }}-stream.qcow2
      {%- else -%}
      centos-{{ os_version }}.qcow2
      {%- endif -%}

- name: "Get latest centos-{{ os_version }} image name"
  shell: >-
    curl -s "{{ baseURI |trim}}" | awk '/GenericCloud.*\.qcow2</ { print $8 }' | cut -d '"' -f 2 | tail -1
  register: latest_centos8

- name: "Fetch latest centos-{{ os_version }} image"
  get_url:
    url: "{{ baseURI |trim}}{{ latest_centos8.stdout |trim}}"
    dest: "{{ basedir }}/images/{{ destImg |trim}}"
    mode: 0664

- name: Set base_image_name fact
  set_fact:
    base_image_name: "{{ destImg |trim}}"
