---
- name: fetch libguestfs appliance
  tags:
    - builder-bootstrap
    - guestfs-appliance
  get_url:
    url: "{{ guestfs_appliance_base_uri }}/appliance-{{ guestfs_appliance_version }}.tar.xz"
    dest: "{{ basedir }}/images/appliance-{{ guestfs_appliance_version }}.tar.xz"
    checksum: "{{ guestfs_appliance_checksum }}"
    owner: "{{ virt_user }}"
  register: appliance_archive

- name: uncompress libguestfs if needed
  tags:
    - builder-bootstrap
    - guestfs-appliance
  when: appliance_archive is changed
  unarchive:
    src: "{{ appliance_archive.dest }}"
    dest: "/usr/local/src/"
    remote_src: true

- name: inject appliance in env
  tags:
    - builder-bootstrap
    - guestfs-appliance
  lineinfile:
    path: /etc/environment
    line: "export LIBGUESTFS_PATH=/usr/local/src/appliance"
