---
- hosts: localhost
  roles:
    - operators

- hosts: builder
  remote_user: root
  vars_files:
    - vars/main.yaml
  roles:
    - deprecations
    - builder
    - nat_vm

- hosts: undercloud
  remote_user: root
  vars_files:
    - vars/main.yaml
  roles:
    - undercloud
