#!/bin/bash

basedir="{{ mirror_base_directory }}"

function centos {
  version="7"
  src="rsync://mirrors.ircam.fr/CentOS"
  dest="${basedir}/CentOS"
  mkdir -p $dest
  rsync -aSHP \
    --delete \
    --exclude "local*" \
    --exclude "isos" \
    "${src}/${version}/" \
    "${dest}/${version}/"
  rsync -aSHP \
    --delete \
    "${src}/RPM-GPG-KEY-CentOS-7" \
    "${dest}/"
}
function epel {
  epel_dest="${basedir}/EPEL"
  epel_src="rsync://pkg.adfinis-sygroup.ch/fedora-epel"
  mkdir -p $epel_dest
  rsync -aSHP \
    --delete \
    "${epel_src}/${version}/x86_64/" \
    "${epel_dest}/${version}/x86_64/"

  rsync -aSHP \
    --delete \
    "${epel_src}/RPM-GPG-KEY-EPEL-7" \
    "$epel_dest"
}
function fedora {
  fedora_version="27 28 29"
  fedora_dest="${basedir}/Fedora"
  fedora_src="rsync://fedora.tu-chemnitz.de/ftp/pub/linux/fedora/linux"

  for i in $fedora_version; do
    mkdir -p "${fedora_dest}/releases/${i}/Everything"
    mkdir -p "${fedora_dest}/updates/${i}/Everything"

    rsync -aSHP \
      --delete \
      --exclude "**/iso" \
      --exclude "**/debug" \
      "${fedora_src}/releases/${i}/Everything/x86_64" \
      "${fedora_dest}/releases/${i}/Everything/"

    case $i in
      27)
        rsync -aSHP \
          --delete \
          --exclude "**/debug" \
          "${fedora_src}/updates/${i}/x86_64" \
          "${fedora_dest}/updates/${i}/"
        ;;
      *)
        rsync -aSHP \
          --delete \
          --exclude "**/debug" \
          "${fedora_src}/updates/${i}/Everything/x86_64" \
          "${fedora_dest}/updates/${i}/Everything/"
        ;;
    esac
  done
}
function dlrn {
  for i in pike queens master; do
    if [ $i == 'pike' ]; then
      deps='https://buildlogs.centos.org/centos/7/cloud/$basearch/openstack-pike/'
    else
      deps="https://trunk.rdoproject.org/centos7-${i}/deps/latest/"
    fi
		cat << EOF > /etc/yum.repos.d/delorean-${i}.repo
[delorean-${i}]
name=dlrn-${i}
baseurl=https://trunk.rdoproject.org/centos7-${i}/current
enabled=0
gpgcheck=0
priority=1

[delorean-${i}-deps]
name=dlrn-${i}-deps
baseurl=$deps
enabled=0
gpgcheck=0
EOF
    reposync -d -l --repoid delorean-${i} --download_path ${basedir}/dlrn/
    createrepo ${basedir}/dlrn/delorean-${i}

    reposync -d -l --repoid delorean-${i}-deps --download_path ${basedir}/dlrn/
    createrepo ${basedir}/dlrn/delorean-${i}-deps
  done
  reposync -d -l --repoid rdo-qemu-ev --download_path ${basedir}/dlrn/
  createrepo ${basedir}/dlrn/rdo-qemu-ev
}

if [ -z $1 ]; then
  r='all'
else
  r=$1
fi

case $r in
  "dlrn")
    dlrn
    ;;
  "centos")
    centos
    ;;
  "fedora")
    fedora
    ;;
  "epel")
    epel
    ;;
  "all")
    dlrn
    centos
    epel
    fedora
    ;;
esac


chcon -R -t httpd_var_lib_t $basedir
