---
- import_tasks: packages.yaml
- import_tasks: config.yaml
- import_tasks: scripts.yaml

- name: Unprovisioned nodes
  tags:
    - lab
    - overcloud
  when:
    - not oc_preprovision|bool
  block:
    - import_tasks: manage-oc-images.yaml
    - import_tasks: upload.yaml
    - import_tasks: networks.yaml
      when:
        - network_data_v2 | bool
    - import_tasks: baremetal.yaml

- name: Deploy all overclouds
  tags:
    - lab
    - overcloud
  loop: "{{ overclouds_range }}"
  loop_control:
    label: "Deploying overcloud {{ item }}"
  include_tasks: deploy.yaml
