---
- name: Provision Networks
  include_role:
    name: tripleo.operator.tripleo_overcloud_network_provision
  vars:
    tripleo_overcloud_network_provision_deployment_file: "/home/stack/oc{{ item }}-network-data.yaml"
    tripleo_overcloud_network_provision_output_file: "/home/stack/overcloud-networks-provisioned-{{ item }}.yaml"
  loop: "{{ overclouds_range }}"

- name: Provision Vips
  include_role:
    name: tripleo.operator.tripleo_overcloud_network_vip_provision
  vars:
    tripleo_overcloud_network_vip_provision_deployment_file: "/home/stack/vip-data-{{ item }}.yaml"
    tripleo_overcloud_network_vip_provision_stack: "overcloud-{{ item }}"
    tripleo_overcloud_network_vip_provision_output_file: "/home/stack/overcloud-vips-provisioned-{{ item }}.yaml"
  loop: "{{ overclouds_range }}"
