---
- name: set proxy for yum
  ini_file:
    backup: true
    path: /etc/yum.conf
    option: proxy
    section: main
    value: "http://{{proxy_host}}"

- name: inject proxy for dnf
  when:
    - dnf_state.stat.exists
  ini_file:
    backup: true
    path: /etc/dnf/dnf.conf
    option: proxy
    section: main
    value: "http://{{proxy_host}}"
