- name: Ensure ownership of the shared ssh key
  file:
    path: /root/.ssh/id_ed25519
    state: file
    owner: root
    group: root
    mode: 0600

- name: create stack user
  tags:
    - lab
    - undercloud-bootstrap
  user:
    comment: "Stack user for tripleo"
    create_home: true
    generate_ssh_key: true
    name: stack
    shell: "/bin/bash"
    ssh_key_bits: 4096
    state: present

- name: create ansible temp dir for stack user
  tags:
    - lab
    - undercloud-bootstrap
  file:
    path: /home/stack/.ansible/tmp
    state: directory
    group: stack
    mode: 0700
    owner: stack

- name: create root keypair
  tags:
    - lab
    - undercloud-bootstrap
  user:
    generate_ssh_key: true
    name: root
    shell: "/bin/bash"
    ssh_key_bits: 4096
    state: present

- name: give sudo accesses
  tags:
    - sudo
    - lab
    - undercloud-bootstrap
  copy:
    dest: /etc/sudoers.d/stack
    src: stack.sudoers
    group: root
    mode: '0440'
    owner: root

- name: copy root authorized_keys to stack user
  tags:
    - lab
    - undercloud-bootstrap
  copy:
    dest: /home/stack/.ssh/authorized_keys
    group: stack
    mode: '0644'
    owner: stack
    remote_src: true
    src: /root/.ssh/authorized_keys

- name: get stack pub key
  tags:
    - lab
    - undercloud-bootstrap
  slurp:
    src: /home/stack/.ssh/id_rsa.pub
  register: stack_pubkey

- name: get root pub key
  tags:
    - lab
    - undercloud-bootstrap
  slurp:
    src: /root/.ssh/id_rsa.pub
  register: root_pubkey

- name: authorize stack user on root via ssh
  tags:
    - lab
    - undercloud-bootstrap
  authorized_key:
    user: root
    key: "{{ stack_pubkey['content'] |b64decode }}"

- name: authorize stack user on stack with ssh
  tags:
    - lab
    - undercloud-bootstrap
  authorized_key:
    user: stack
    key: "{{ stack_pubkey['content'] |b64decode }}"

- name: authorize root user on stack via ssh
  tags:
    - lab
    - undercloud-bootstrap
  authorized_key:
    user: stack
    key: "{{ root_pubkey['content'] |b64decode }}"

- name: authorize root user on root via ssh
  tags:
    - lab
    - undercloud-bootstrap
  authorized_key:
    user: root
    key: "{{ root_pubkey['content'] |b64decode }}"

- name: Copy shared key from root to stack
  tags:
    - lab
    - undercloud-bootstrap
    - ssh-key
  copy:
    remote_src: true
    src: /root/.ssh/id_ed25519
    dest: /home/stack/.ssh/id_ed25519
    owner: stack
    group: stack
    mode: 0600

- name: Authorize custom keys on the undercloud
  tags:
    - lab
    - undercloud-bootstrap
    - ssh-key
  authorized_key:
    user: stack
    key: "{{ item }}"
  loop: "{{ stack_ssh_keys | default([]) }}"

- name: ensure free access to the overcloud nodes
  tags:
    - lab
    - undercloud-bootstrap
  copy:
    dest: /home/stack/.ssh/config
    src: ssh_config
    owner: stack
    group: stack
    mode: 0640
